Mangatube: Fix website
manga-download/haruneko pull request #818
Opened 2024-10-10 15:41 UTC by MikeZeDev

2024-10-17 18:02 UTC, ronny1982 requested changes

2024-10-17 20:56 UTC, ronny1982 approved these changes

2024-10-18 08:57 UTC, MikeZeDev commented on web/src/engine/websites/MangaTube_e2e.ts
> +        title: '154.5 Banketteinladung (2)',
I knew that but Idk where this Kapital come from now, there are inconsistencies like this too

![image](https://github.com/user-attachments/assets/8471a4a4-29ca-4fc2-adf7-2626aaae8f0c)

2024-10-18 09:15 UTC, MikeZeDev commented on web/src/engine/websites/MangaTube_e2e.ts
> +        title: '154.5 Banketteinladung (2)',
Another one 

![image](https://github.com/user-attachments/assets/5f1afea3-1691-45d9-b82a-b62671c26a92)

2024-10-18 10:46 UTC, MikeZeDev commented on web/src/engine/websites/MangaTube_e2e.ts
> +        title: '154.5 Banketteinladung (2)',
Ok i have found the trick BUT respecting new website naming scheme will break download history anyway, as they now sometimes add '-' between numbers and title.

2024-10-18 14:30 UTC, merged