[jsPdf] workaround for non compatibles JPEG
manga-download/haruneko pull request #837
Opened 2024-10-20 15:17 UTC by MikeZeDev

Closes https://github.com/manga-download/haruneko/issues/797

2024-10-23 21:04 UTC, ronny1982 requested changes

2024-10-24 07:46 UTC, MikeZeDev commented on web/src/engine/exporters/PortableDocumentFormatExporter.ts
> +     * Test if JPEG data is compatible with JsPDF "headers check"
its a problem with jspdf. I've checked for other libraries first, i was not convinced.

2024-10-24 11:41 UTC, MikeZeDev commented on web/src/engine/exporters/PortableDocumentFormatExporter.ts
> +        const imageData = new Uint8Array(await data.arrayBuffer());
Yeah, quite a valid concern.

```ts
    const { data } = await super.ReadTempImageData(sourceFileList.get(index), index, digits);
    const bitmap = await createImageBitmap(data);
    try {
        const { width, height } = bitmap;
        // Conversion of unsupported images via jsPDF is slow and produces a large PDF => Using own implementation of image conversion
        let buffer = new Uint8Array(await data.arrayBuffer());
        buffer = await this.CheckImageCompatibility(data.type, buffer) ? buffer : new Uint8Array(await (await ConvertBitmap(bitmap, 'image/jpeg', 0.95)).arrayBuffer());
        return { width, height, data: buffer };
    } finally {
        bitmap.close();
    }
```

2024-11-02 01:51 UTC, ronny1982 approved these changes

2024-11-02 09:28 UTC, merged